### ISSUE TITLE
offer 展示列表，在发生查找的时候，页面出现不一致的情况

### ISSUE THREAD

**Issue by xxl4** [xxl4/adoffer#25]
![image](https://github.com/xxl4/adoffer/assets/34465153/11f74875-7d1f-41ee-b8b4-3bf76cb61a27)

查找后的页面显示

![image](https://github.com/xxl4/adoffer/assets/34465153/f5534225-bbc8-441e-ad00-bc0454509c60)

**Comment by gekaiyuan** [comment]
源网站处理的比较复杂，查找时使用了左右数据分开处理的方式来实现
