### ISSUE TITLE
Reports 中没有欺诈数据？ 

### ISSUE THREAD

**Issue by xxl4** [xxl4/adoffer#44]
Reports 中的欺诈数据需要有标识的功能，主要是针对于有异常的订单需要有一个标识功能，从而在页面中显示出来。这块方便账单核对等情况。

![image](https://github.com/xxl4/adoffer/assets/34465153/34e0edaf-6139-4a8e-b0d2-e4328b95d4aa)

**Comment by gekaiyuan** [comment]
添加了fraud_data列表，暂时添加了三种欺诈订单类别，如有更改后续做维护
